# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/


# Smooth Scroll on clicking nav items
$('nav a').click ->
  $href = $(this).attr('href')
  $('body').stop().animate { scrollTop: $($href).offset().top }, 1000
  false
# back to top
$('#toTop a').click ->
  $('body').animate { scrollTop: 0 }, 1000
  false
# Parallaxing + add class active on scroll
$(document).scroll ->
  # parallaxing
  $movebg = $(window).scrollTop() * -0.3
  $('.portion').css 'background-positionY', $movebg + 'px'
  # add class active to nav a on scroll
  scrollPos = $(document).scrollTop() + 100
  $('nav a').each ->
    currLink = $(this)
    refElement = $(currLink.attr('href'))
    if refElement.position().top <= scrollPos and refElement.position().top + refElement.height() > scrollPos
      $('nav a').removeClass 'active'
      currLink.addClass 'active'
    return
  # changing padding of nav a on scroll
  if scrollPos > 250
    $('nav a').addClass 'small'
    $('nav img').addClass 'move'
    $('nav span').removeClass 'movetext'
  else
    $('nav a').removeClass 'small'
    $('nav img').removeClass 'move'
    $('nav span').addClass 'movetext'
  return

# ---
# generated by js2coffee 2.2.0